export const MAJOR_MAP: Record<string, string[]> = {
  Bachelors: [
    "Computer Science",
    "Business Administration",
    "Psychology",
    "Economics",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Biology",
    "English Literature",
    "Political Science",
    "Architecture",
  ],
  Masters: [
    "Computer Science",
    "Data Science",
    "Artificial Intelligence",
    "MBA",
    "Finance",
    "Public Health",
    "Mechanical Engineering",
    "Civil Engineering",
    "Cybersecurity",
    "Digital Marketing",
  ],
  PhD: [
    "Computer Science",
    "Physics",
    "Mathematics",
    "Biology",
    "History",
    "Philosophy",
    "Economics",
    "Chemistry",
  ],
  MBA: [
    "General Management",
    "Finance",
    "Marketing",
    "Operations",
    "Strategy",
    "Entrepreneurship",
    "Human Resources",
  ],
};

export const DEGREE_OPTIONS = ["Bachelors", "Masters", "PhD", "MBA"];
